package com.example.demo.student;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.time.Month;
import java.util.List;

@Configuration
public class StudentConfig {

    /*
        JPA Repository is a way of storing our objects into the DB

        - Cant make the POST more interactive with an actual front end
        - Tried testing it staticly but don't have the HTTP Client

        Testing POST using postman and put in the body (name, email, dob)
     */

    // Beans are basically java objects
    @Bean  
    CommandLineRunner commandLineRunner(
            StudentRepository repository){
        return args -> {
            Student john = new Student( // id generated by DB
                    "John",
                    "john@gmail.com",
                    LocalDate.of(1999, Month.AUGUST,5)
            );

            Student alex = new Student(
                    "Alex",
                    "alex@gmail.com",
                    LocalDate.of(2004, Month.JANUARY, 5)
            );

            repository.saveAll(
                    List.of(john,alex)
            );
        };
    }
}
